const GOLD_API_BASE = 'https://api.gold-api.com';
const PERIODS = Object.freeze({
  '24h': { groupBy: 'minute', spanSeconds: 24 * 60 * 60, sampleMinutes: 5, cacheSeconds: 300 },
  '7d': { groupBy: 'hour', spanSeconds: 7 * 24 * 60 * 60, cacheSeconds: 900 },
  '30d': { groupBy: 'hour', spanSeconds: 30 * 24 * 60 * 60, cacheSeconds: 1800 },
  '90d': { groupBy: 'day', spanSeconds: 90 * 24 * 60 * 60, cacheSeconds: 21600 },
  '1y': { groupBy: 'day', spanSeconds: 365 * 24 * 60 * 60, cacheSeconds: 21600 },
  // Limite tecnico della fonte, non promessa di anni di copertura.
  'all': { groupBy: 'month', startYear: 1980, cacheSeconds: 86400 }
});
function setCors(res) { res.setHeader('Access-Control-Allow-Origin', '*'); res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type'); res.setHeader('X-Content-Type-Options', 'nosniff'); }
function startFor(config, nowMs) { return config.startYear ? Math.floor(Date.UTC(config.startYear, 0, 1) / 1000) : Math.floor(nowMs / 1000) - config.spanSeconds; }
function bucketTimestamp(row, groupBy) { const raw = groupBy === 'minute' ? row.date_minute : groupBy === 'hour' ? row.date_hour : groupBy === 'day' ? row.day : row.year_month; if (!raw) return null; const iso = groupBy === 'minute' ? raw.replace(' ', 'T') + ':00Z' : groupBy === 'hour' ? raw.replace(' ', 'T') + ':00:00Z' : groupBy === 'day' ? raw.slice(0, 10) + 'T00:00:00Z' : raw.slice(0, 7) + '-01T00:00:00Z'; const ts = Date.parse(iso); return Number.isFinite(ts) ? ts : null; }
async function fetchSeries(symbol, config, startTimestamp, endTimestamp, apiKey) { const url = new URL('/history', GOLD_API_BASE); url.searchParams.set('symbol', symbol); url.searchParams.set('startTimestamp', String(startTimestamp)); url.searchParams.set('endTimestamp', String(endTimestamp)); url.searchParams.set('groupBy', config.groupBy); url.searchParams.set('aggregation', 'avg'); url.searchParams.set('orderBy', 'asc'); const response = await fetch(url, { headers: { 'x-api-key': apiKey } }); if (!response.ok) throw new Error(`Gold API ${symbol}: HTTP ${response.status}`); const payload = await response.json(); if (!Array.isArray(payload)) throw new Error(`Gold API ${symbol}: risposta non valida`); return payload.map(row => ({ ts: bucketTimestamp(row, config.groupBy), price: Number(row.avg_price) })).filter(point => Number.isFinite(point.ts) && Number.isFinite(point.price) && point.price > 0); }
function combineSeries(gold, silver, platinum) { const rows = new Map(), add = (series, field) => series.forEach(point => { const row = rows.get(point.ts) || { ts: point.ts, goldUsd: null, silverUsd: null, platinumUsd: null }; row[field] = point.price; rows.set(point.ts, row); }); add(gold, 'goldUsd'); add(silver, 'silverUsd'); add(platinum, 'platinumUsd'); return [...rows.values()].sort((a, b) => a.ts - b.ts); }
function sampleFiveMinutes(points, startTimestamp, endTimestamp) { const stepMs = 300000, startMs = startTimestamp * 1000, endMs = endTimestamp * 1000; return points.filter(p => p.ts >= startMs && p.ts <= endMs && p.ts % stepMs === 0).filter((p, i, a) => i === 0 || p.ts !== a[i - 1].ts); }
function hasCompleteFiveMinuteGrid(points, startTimestamp, endTimestamp) { const stepMs = 300000, startMs = startTimestamp * 1000, expected = Math.floor((endTimestamp * 1000 - startMs) / stepMs) + 1; return points.length === expected && points.every((p, i) => p.ts === startMs + i * stepMs && p.goldUsd > 0 && p.silverUsd > 0 && p.platinumUsd > 0); }
export default async function handler(req, res) { setCors(res); if (req.method === 'OPTIONS') return res.status(204).end(); if (req.method !== 'GET') return res.status(405).json({ error: 'Metodo non consentito' }); const period = String(req.query.period || '7d').toLowerCase(), config = PERIODS[period]; if (!config) return res.status(400).json({ error: 'Periodo non valido' }); const apiKey = process.env.GOLD_API_KEY; if (!apiKey) return res.status(503).json({ error: 'Servizio dati non configurato' }); const nowMs = Date.now(); let endTimestamp = Math.floor(nowMs / 1000), startTimestamp = startFor(config, nowMs), fetchStartTimestamp = startTimestamp; if (config.sampleMinutes) { const step = config.sampleMinutes * 60; endTimestamp = Math.floor(endTimestamp / step) * step - step; startTimestamp = endTimestamp - config.spanSeconds; fetchStartTimestamp = startTimestamp - 1800; } try { const [gold, silver, platinum] = await Promise.all([fetchSeries('XAU', config, fetchStartTimestamp, endTimestamp, apiKey), fetchSeries('XAG', config, fetchStartTimestamp, endTimestamp, apiKey), fetchSeries('XPT', config, fetchStartTimestamp, endTimestamp, apiKey)]); if (!gold.length || !silver.length || !platinum.length) throw new Error('Una o piu serie storiche non sono disponibili');
    let points = combineSeries(gold, silver, platinum); if (config.sampleMinutes === 5) { const stepMs = 300000, latest = points.filter(p => p.ts <= endTimestamp * 1000 && p.ts % stepMs === 0 && p.goldUsd > 0 && p.silverUsd > 0 && p.platinumUsd > 0).pop(); if (!latest || endTimestamp * 1000 - latest.ts > 1800000) throw new Error('Dati intraday troppo distanti dall’ora corrente'); endTimestamp = Math.floor(latest.ts / 1000); startTimestamp = endTimestamp - config.spanSeconds; points = sampleFiveMinutes(points, startTimestamp, endTimestamp); if (!hasCompleteFiveMinuteGrid(points, startTimestamp, endTimestamp)) throw new Error('Griglia a 5 minuti incompleta'); } if (!points.length) throw new Error('Nessun punto storico disponibile'); res.setHeader('Cache-Control', `public, s-maxage=${config.cacheSeconds}, stale-while-revalidate=${Math.max(60, Math.floor(config.cacheSeconds / 2))}`); return res.status(200).json({ version: 1, source: 'Gold API', period, resolution: config.sampleMinutes ? `${config.sampleMinutes}m` : config.groupBy, requestedStart: startTimestamp * 1000, requestedEnd: endTimestamp * 1000, actualStart: points[0].ts, actualEnd: points[points.length - 1].ts, points }); } catch (error) { console.error(error); res.setHeader('Cache-Control', 'no-store'); return res.status(502).json({ error: 'Dati storici temporaneamente non disponibili' }); } }
